#ifndef DOME_CONTROLLER_HTML_H
#define DOME_CONTROLLER_HTML_H

const char DOME_CONTROLLER_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
  "<title>RTI-Zone Dome Controller</title>\n"
  "\n"
  "<style>\n"
  "  :root {\n"
  "    --bg:        #080c14;\n"
  "    --surface:   #0d1526;\n"
  "    --panel:     #111d35;\n"
  "    --border:    #1e3a6a;\n"
  "    --accent:    #00d4ff;\n"
  "    --accent2:   #ff6b35;\n"
  "    --green:     #39ff8f;\n"
  "    --red:       #ff3d5a;\n"
  "    --yellow:    #ffd166;\n"
  "    --text:      #c8deff;\n"
  "    --muted:     #4a6a9a;\n"
  "    --glow:      0 0 12px rgba(0,212,255,.45);\n"
  "    --glow2:     0 0 12px rgba(255,107,53,.5);\n"
  "  }\n"
  "\n"
  "  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
  "\n"
  "  body {\n"
  "    background: var(--bg);\n"
  "    color: var(--text);\n"
  "    font-family: 'Courier New', Courier, monospace;\n"
  "    min-height: 100vh;\n"
  "    overflow-x: hidden;\n"
  "  }\n"
  "\n"
  "  /* Starfield */\n"
  "  body::before {\n"
  "    content: '';\n"
  "    position: fixed; inset: 0; z-index: 0;\n"
  "    background-image:\n"
  "      radial-gradient(1px 1px at 20% 30%, rgba(255,255,255,.7) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 60% 10%, rgba(255,255,255,.5) 0%, transparent 100%),\n"
  "      radial-gradient(1.5px 1.5px at 80% 50%, rgba(255,255,255,.6) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 40% 80%, rgba(255,255,255,.4) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 90% 70%, rgba(255,255,255,.5) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 10% 60%, rgba(255,255,255,.6) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 55% 45%, rgba(255,255,255,.3) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 30% 15%, rgba(255,255,255,.4) 0%, transparent 100%),\n"
  "      radial-gradient(1.5px 1.5px at 70% 85%, rgba(200,220,255,.6) 0%, transparent 100%),\n"
  "      radial-gradient(1px 1px at 15% 90%, rgba(255,255,255,.3) 0%, transparent 100%);\n"
  "    pointer-events: none;\n"
  "  }\n"
  "\n"
  "  .shell {\n"
  "    position: relative; z-index: 1;\n"
  "    max-width: 1200px;\n"
  "    margin: 0 auto;\n"
  "    padding: 24px 20px 60px;\n"
  "  }\n"
  "\n"
  "  /* HEADER */\n"
  "  header {\n"
  "    display: flex; align-items: center; justify-content: space-between;\n"
  "    border-bottom: 1px solid var(--border);\n"
  "    padding-bottom: 20px; margin-bottom: 32px;\n"
  "  }\n"
  "  .logo { display: flex; align-items: center; gap: 14px; }\n"
  "  .dome-icon {\n"
  "    width: 52px; height: 52px;\n"
  "    position: relative;\n"
  "  }\n"
  "  .dome-icon svg { width: 100%; height: 100%; }\n"
  "  h1 {\n"
  "    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', Arial, sans-serif;\n"
  "    font-size: 1.25rem;\n"
  "    font-weight: 800;\n"
  "    letter-spacing: .08em;\n"
  "    color: var(--accent);\n"
  "    text-shadow: var(--glow);\n"
  "    line-height: 1.2;\n"
  "  }\n"
  "  h1 span { display: block; font-size: .7rem; color: var(--muted); font-weight: 400; letter-spacing: .15em; }\n"
  "\n"
  "  .host-bar {\n"
  "    display: flex; align-items: center; gap: 10px;\n"
  "  }\n"
  "\n"
  "  #conn-status {\n"
  "    width: 10px; height: 10px; border-radius: 50%;\n"
  "    background: var(--muted);\n"
  "    box-shadow: 0 0 6px var(--muted);\n"
  "    transition: background .4s, box-shadow .4s;\n"
  "  }\n"
  "  #conn-status.ok  { background: var(--green); box-shadow: 0 0 8px var(--green); }\n"
  "  #conn-status.err { background: var(--red);   box-shadow: 0 0 8px var(--red); }\n"
  "\n"
  "  /* TABS */\n"
  "  .tabs {\n"
  "    display: flex; gap: 4px;\n"
  "    border-bottom: 1px solid var(--border);\n"
  "    margin-bottom: 28px;\n"
  "  }\n"
  "  .tab-btn {\n"
  "    background: none; border: none;\n"
  "    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', Arial, sans-serif;\n"
  "    font-size: .65rem; font-weight: 600;\n"
  "    letter-spacing: .1em;\n"
  "    color: var(--muted);\n"
  "    padding: 10px 18px;\n"
  "    cursor: pointer;\n"
  "    border-bottom: 2px solid transparent;\n"
  "    transition: color .2s, border-color .2s;\n"
  "    text-transform: uppercase;\n"
  "  }\n"
  "  .tab-btn:hover { color: var(--text); }\n"
  "  .tab-btn.active { color: var(--accent); border-bottom-color: var(--accent); }\n"
  "\n"
  "  .tab-pane { display: none; }\n"
  "  .tab-pane.active { display: block; }\n"
  "\n"
  "  /* GRID */\n"
  "  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 18px; }\n"
  "\n"
  "  /* CARD */\n"
  "  .card {\n"
  "    background: var(--surface);\n"
  "    border: 1px solid var(--border);\n"
  "    border-radius: 8px;\n"
  "    overflow: hidden;\n"
  "    transition: border-color .2s;\n"
  "  }\n"
  "  .card:hover { border-color: rgba(0,212,255,.35); }\n"
  "  .card-head {\n"
  "    display: flex; align-items: center; justify-content: space-between;\n"
  "    padding: 12px 16px;\n"
  "    background: var(--panel);\n"
  "    border-bottom: 1px solid var(--border);\n"
  "  }\n"
  "  .card-title {\n"
  "    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', Arial, sans-serif;\n"
  "    font-size: .62rem;\n"
  "    font-weight: 600;\n"
  "    letter-spacing: .12em;\n"
  "    color: var(--muted);\n"
  "    text-transform: uppercase;\n"
  "  }\n"
  "  .method-badge {\n"
  "    font-size: .6rem; padding: 2px 7px; border-radius: 3px;\n"
  "    font-weight: 700; letter-spacing: .05em;\n"
  "  }\n"
  "  .badge-get  { background: rgba(57,255,143,.15);  color: var(--green); }\n"
  "  .badge-put  { background: rgba(255,107,53,.15);  color: var(--accent2); }\n"
  "  .badge-both { background: rgba(0,212,255,.12);   color: var(--accent); }\n"
  "\n"
  "  .card-body { padding: 14px 16px; }\n"
  "\n"
  "  .val-display {\n"
  "    font-size: 1.4rem;\n"
  "    color: var(--accent);\n"
  "    text-shadow: var(--glow);\n"
  "    letter-spacing: .06em;\n"
  "    min-height: 36px;\n"
  "    word-break: break-all;\n"
  "  }\n"
  "  .val-display.unknown { color: var(--muted); font-size: 1rem; }\n"
  "\n"
  "  .card-actions { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }\n"
  "\n"
  "  input[type=\"text\"], input[type=\"number\"], select {\n"
  "    background: var(--panel); border: 1px solid var(--border);\n"
  "    color: var(--text); font-family: 'Courier New', Courier, monospace;\n"
  "    font-size: .82rem; padding: 6px 10px; border-radius: 4px;\n"
  "    outline: none; transition: border-color .2s;\n"
  "    width: 130px;\n"
  "  }\n"
  "  input[type=\"text\"]:focus, input[type=\"number\"]:focus, select:focus {\n"
  "    border-color: var(--accent); box-shadow: var(--glow);\n"
  "  }\n"
  "  select option { background: var(--panel); }\n"
  "\n"
  "  /* BUTTONS */\n"
  "  .btn {\n"
  "    font-family: 'Courier New', Courier, monospace;\n"
  "    font-size: .78rem; letter-spacing: .05em;\n"
  "    padding: 6px 14px; border-radius: 4px;\n"
  "    border: 1px solid; cursor: pointer;\n"
  "    transition: background .15s, box-shadow .15s, opacity .15s;\n"
  "  }\n"
  "  .btn:active { opacity: .75; }\n"
  "  .btn-get {\n"
  "    background: rgba(57,255,143,.08);\n"
  "    border-color: var(--green); color: var(--green);\n"
  "  }\n"
  "  .btn-get:hover { background: rgba(57,255,143,.2); box-shadow: 0 0 8px rgba(57,255,143,.4); }\n"
  "\n"
  "  .btn-put {\n"
  "    background: rgba(255,107,53,.08);\n"
  "    border-color: var(--accent2); color: var(--accent2);\n"
  "  }\n"
  "  .btn-put:hover { background: rgba(255,107,53,.2); box-shadow: 0 0 8px rgba(255,107,53,.4); }\n"
  "\n"
  "  .btn-danger {\n"
  "    background: rgba(255,61,90,.08);\n"
  "    border-color: var(--red); color: var(--red);\n"
  "  }\n"
  "  .btn-danger:hover { background: rgba(255,61,90,.2); box-shadow: 0 0 8px rgba(255,61,90,.4); }\n"
  "\n"
  "  /* LOG */\n"
  "  .log-panel {\n"
  "    margin-top: 32px;\n"
  "    background: var(--surface);\n"
  "    border: 1px solid var(--border);\n"
  "    border-radius: 8px;\n"
  "    overflow: hidden;\n"
  "  }\n"
  "  .log-head {\n"
  "    display: flex; align-items: center; justify-content: space-between;\n"
  "    padding: 10px 16px;\n"
  "    background: var(--panel);\n"
  "    border-bottom: 1px solid var(--border);\n"
  "  }\n"
  "  .log-head-title {\n"
  "    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', Arial, sans-serif;\n"
  "    font-size: .6rem; letter-spacing: .14em; color: var(--muted);\n"
  "  }\n"
  "  #log {\n"
  "    height: 200px; overflow-y: auto;\n"
  "    padding: 12px 16px;\n"
  "    font-size: .75rem; line-height: 1.7;\n"
  "  }\n"
  "  #log::-webkit-scrollbar { width: 6px; }\n"
  "  #log::-webkit-scrollbar-track { background: var(--surface); }\n"
  "  #log::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }\n"
  "\n"
  "  .log-entry { display: flex; gap: 12px; }\n"
  "  .log-ts  { color: var(--muted); flex-shrink: 0; }\n"
  "  .log-ok  { color: var(--green); }\n"
  "  .log-err { color: var(--red); }\n"
  "  .log-info{ color: var(--accent); }\n"
  "\n"
  "  /* Loading spinner */\n"
  "  .spinner {\n"
  "    display: inline-block;\n"
  "    width: 14px; height: 14px;\n"
  "    border: 2px solid var(--border);\n"
  "    border-top-color: var(--accent);\n"
  "    border-radius: 50%;\n"
  "    animation: spin .6s linear infinite;\n"
  "    vertical-align: middle;\n"
  "  }\n"
  "  @keyframes spin { to { transform: rotate(360deg); } }\n"
  "\n"
  "  /* Section subtitle */\n"
  "  .section-label {\n"
  "    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', Arial, sans-serif;\n"
  "    font-size: .6rem; letter-spacing: .18em;\n"
  "    color: var(--muted); text-transform: uppercase;\n"
  "    margin-bottom: 14px;\n"
  "    display: flex; align-items: center; gap: 10px;\n"
  "  }\n"
  "  .section-label::after {\n"
  "    content: ''; flex: 1; height: 1px;\n"
  "    background: linear-gradient(to right, var(--border), transparent);\n"
  "  }\n"
  "\n"
  "  /* Dome visual */\n"
  "  .dome-visual {\n"
  "    display: flex; justify-content: center; align-items: center;\n"
  "    padding: 24px 0 12px;\n"
  "  }\n"
  "  .dome-svg-wrap { position: relative; width: 200px; }\n"
  "  #az-label {\n"
  "    position: absolute; top: 50%; left: 50%;\n"
  "    transform: translate(-50%, -30%);\n"
  "    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', Arial, sans-serif;\n"
  "    font-size: 1.1rem; font-weight: 800;\n"
  "    color: var(--accent); text-shadow: var(--glow);\n"
  "    text-align: center; pointer-events: none;\n"
  "  }\n"
  "  #az-label small { display: block; font-size: .55rem; color: var(--muted); font-weight: 400; }\n"
  "\n"
  "  .status-row { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 20px; }\n"
  "  .status-chip {\n"
  "    background: var(--panel); border: 1px solid var(--border);\n"
  "    border-radius: 20px; padding: 5px 14px;\n"
  "    font-size: .72rem; display: flex; align-items: center; gap: 7px;\n"
  "  }\n"
  "  .chip-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--muted); flex-shrink: 0; }\n"
  "  .chip-dot.on  { background: var(--green); box-shadow: 0 0 6px var(--green); }\n"
  "  .chip-dot.off { background: var(--red);   box-shadow: 0 0 6px var(--red); }\n"
  "  .chip-dot.warn{ background: var(--yellow);box-shadow: 0 0 6px var(--yellow); }\n"
  "\n"
  "  /* Responsive */\n"
  "  @media(max-width:600px) {\n"
  "    header { flex-direction: column; align-items: flex-start; gap: 16px; }\n"
  "    .tab-btn { padding: 8px 10px; font-size: .58rem; }\n"
  "  }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div class=\"shell\">\n"
  "\n"
  "  <!-- HEADER -->\n"
  "  <header>\n"
  "    <div class=\"logo\">\n"
  "      <div class=\"dome-icon\">\n"
  "        <svg viewBox=\"0 0 52 52\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"
  "          <path d=\"M6 36 Q6 10 26 10 Q46 10 46 36\" stroke=\"#00d4ff\" stroke-width=\"2\" fill=\"rgba(0,212,255,.07)\"/>\n"
  "          <rect x=\"4\" y=\"36\" width=\"44\" height=\"5\" rx=\"2\" fill=\"#1e3a6a\"/>\n"
  "          <line x1=\"26\" y1=\"10\" x2=\"26\" y2=\"36\" stroke=\"#1e3a6a\" stroke-width=\"1\" stroke-dasharray=\"3,3\"/>\n"
  "          <circle cx=\"26\" cy=\"36\" r=\"3\" fill=\"#00d4ff\" opacity=\".6\"/>\n"
  "          <!-- rotating arrow -->\n"
  "          <path id=\"hdr-arrow\" d=\"M14 30 A14 14 0 0 1 38 30\" stroke=\"#ff6b35\" stroke-width=\"1.5\"\n"
  "                fill=\"none\" stroke-dasharray=\"4,3\" marker-end=\"url(#arrowhead)\"/>\n"
  "          <defs>\n"
  "            <marker id=\"arrowhead\" markerWidth=\"5\" markerHeight=\"5\" refX=\"2.5\" refY=\"2.5\" orient=\"auto\">\n"
  "              <polygon points=\"0 0, 5 2.5, 0 5\" fill=\"#ff6b35\"/>\n"
  "            </marker>\n"
  "          </defs>\n"
  "        </svg>\n"
  "      </div>\n"
  "      <h1>RTI-Zone Dome Controller<span>ASCOM ALPACA COMPATIBLE</span></h1>\n"
  "    </div>\n"
  "    <div class=\"host-bar\">\n"
  "      <div id=\"conn-status\" title=\"Connection status\"></div>\n"
  "    </div>\n"
  "  </header>\n"
  "\n"
  "  <!-- TABS -->\n"
  "  <div class=\"tabs\">\n"
  "    <button class=\"tab-btn active\" data-tab=\"overview\">Overview</button>\n"
  "    <button class=\"tab-btn\" data-tab=\"positions\">Positions</button>\n"
  "    <button class=\"tab-btn\" data-tab=\"rotation\">Rotation</button>\n"
  "    <button class=\"tab-btn\" data-tab=\"shutter\">Shutter</button>\n"
  "    <button class=\"tab-btn\" data-tab=\"network\">Network</button>\n"
  "  </div>\n"
  "\n"
  "  <!-- ===== OVERVIEW TAB ===== -->\n"
  "  <div class=\"tab-pane active\" id=\"tab-overview\">\n"
  "\n"
  "    <div class=\"dome-visual\">\n"
  "      <div class=\"dome-svg-wrap\">\n"
  "        <svg id=\"dome-svg\" viewBox=\"0 0 200 160\" xmlns=\"http://www.w3.org/2000/svg\">\n"
  "          <!-- ground -->\n"
  "          <rect x=\"10\" y=\"120\" width=\"180\" height=\"8\" rx=\"3\" fill=\"#1e3a6a\" opacity=\".5\"/>\n"
  "          <!-- dome body -->\n"
  "          <path d=\"M30 120 Q30 30 100 30 Q170 30 170 120\" fill=\"rgba(13,21,38,.8)\" stroke=\"#1e3a6a\" stroke-width=\"1.5\"/>\n"
  "          <!-- shutter opening -->\n"
  "          <path id=\"shutter-vis\" d=\"M80 120 Q80 30 100 30 Q120 30 120 120\" fill=\"rgba(0,212,255,.05)\" stroke=\"rgba(0,212,255,.25)\" stroke-width=\"1\"/>\n"
  "          <!-- azimuth pointer -->\n"
  "          <g id=\"az-pointer\" style=\"transform-origin:100px 120px; transform:rotate(0deg); transition:transform 0.8s ease;\">\n"
  "            <line x1=\"100\" y1=\"120\" x2=\"100\" y2=\"52\" stroke=\"#00d4ff\" stroke-width=\"2\" opacity=\".8\"/>\n"
  "            <polygon points=\"100,44 96,56 104,56\" fill=\"#00d4ff\" opacity=\".9\"/>\n"
  "          </g>\n"
  "          <!-- compass ticks -->\n"
  "          <text x=\"100\" y=\"22\" text-anchor=\"middle\" fill=\"#4a6a9a\" font-size=\"9\" font-family=\"'Courier New', monospace\">N</text>\n"
  "          <text x=\"176\" y=\"78\" text-anchor=\"middle\" fill=\"#4a6a9a\" font-size=\"9\" font-family=\"'Courier New', monospace\">E</text>\n"
  "          <text x=\"24\"  y=\"78\" text-anchor=\"middle\" fill=\"#4a6a9a\" font-size=\"9\" font-family=\"'Courier New', monospace\">W</text>\n"
  "        </svg>\n"
  "        <div id=\"az-label\">--°<small>AZIMUTH</small></div>\n"
  "      </div>\n"
  "    </div>\n"
  "\n"
  "    <!-- Status chips -->\n"
  "    <div class=\"status-row\" id=\"status-row\">\n"
  "      <div class=\"status-chip\"><div class=\"chip-dot\" id=\"chip-calib\"></div>Calibration</div>\n"
  "      <div class=\"status-chip\"><div class=\"chip-dot\" id=\"chip-shutter\"></div>Shutter</div>\n"
  "      <div class=\"status-chip\"><div class=\"chip-dot\" id=\"chip-env\"></div>Environment</div>\n"
  "      <div class=\"status-chip\"><div class=\"chip-dot\" id=\"chip-dhcp\"></div>DHCP</div>\n"
  "    </div>\n"
  "\n"
  "    <div class=\"section-label\">Quick Refresh</div>\n"
  "    <div class=\"card-actions\">\n"
  "      <button class=\"btn btn-get\" onclick=\"refreshOverview()\">↻ Refresh All</button>\n"
  "    </div>\n"
  "  </div>\n"
  "\n"
  "  <!-- ===== POSITIONS TAB ===== -->\n"
  "  <div class=\"tab-pane\" id=\"tab-positions\">\n"
  "    <div class=\"section-label\">Position Settings</div>\n"
  "    <div class=\"grid\">\n"
  "\n"
  "      <!-- Home position -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Home Position</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-home\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/homePosition','val-home',v=>v.value+'°')\">GET</button>\n"
  "            <input type=\"number\" id=\"in-home\" placeholder=\"degrees\" step=\"0.1\" min=\"0\" max=\"360\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/homePosition','in-home','val-home',v=>v.value+'°')\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Park position -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Park Position</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-park\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/parkPosition','val-park',v=>v.value+'°')\">GET</button>\n"
  "            <input type=\"number\" id=\"in-park\" placeholder=\"degrees\" step=\"0.1\" min=\"0\" max=\"360\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/parkPosition','in-park','val-park',v=>v.value+'°')\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Reverse direction -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Reverse Direction</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-reverse\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/reverseDirection','val-reverse',v=>JSON.stringify(v))\">GET</button>\n"
  "            <select id=\"in-reverse\">\n"
  "              <option value=\"false\">Normal</option>\n"
  "              <option value=\"true\">Reversed</option>\n"
  "            </select>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/reverseDirection','in-reverse','val-reverse',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Unsafe action -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Unsafe Weather Action</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-unsafe\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/unsafeDomeAction','val-unsafe',v=>JSON.stringify(v))\">GET</button>\n"
  "            <select id=\"in-unsafe\">\n"
  "              <option value=\"DO_NOTHING\">DO_NOTHING</option>\n"
  "              <option value=\"HOME\">HOME</option>\n"
  "              <option value=\"PARK\">PARK</option>\n"
  "            </select>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/unsafeDomeAction','in-unsafe','val-unsafe',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Env condition (GET only) -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Environment Condition</span>\n"
  "          <span class=\"method-badge badge-get\">GET</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-env\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/envCondition','val-env',v=>JSON.stringify(v))\">GET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "    </div>\n"
  "  </div>\n"
  "\n"
  "  <!-- ===== ROTATION TAB ===== -->\n"
  "  <div class=\"tab-pane\" id=\"tab-rotation\">\n"
  "    <div class=\"section-label\">Rotation Controller</div>\n"
  "    <div class=\"grid\">\n"
  "\n"
  "      <!-- Calibration status -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Calibration Status</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-calib\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/domeCalibrate','val-calib',v=>v.value)\">GET</button>\n"
  "            <select id=\"in-calib\">\n"
  "              <option value=\"start\">Start</option>\n"
  "              <option value=\"stop\">Stop</option>\n"
  "            </select>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/domeCalibrate','in-calib','val-calib',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Steps per revolution -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Steps / Revolution</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-spr\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/stepPerRevolution','val-spr',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"number\" id=\"in-spr\" placeholder=\"steps\" min=\"1\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/stepPerRevolution','in-spr','val-spr',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Rotation speed -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Rotation Speed (steps/s)</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-rspeed\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/rotationSpeed','val-rspeed',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"number\" id=\"in-rspeed\" placeholder=\"steps/s\" min=\"1\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/rotationSpeed','in-rspeed','val-rspeed',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Rotation acceleration -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Rotation Acceleration (steps/s²)</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-racc\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/rotationAcceleration','val-racc',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"number\" id=\"in-racc\" placeholder=\"steps/s²\" min=\"1\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/rotationAcceleration','in-racc','val-racc',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Restore defaults -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Restore Motor Defaults</span>\n"
  "          <span class=\"method-badge badge-put\">PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div style=\"font-size:.8rem;color:var(--muted);margin-bottom:12px;\">\n"
  "            Resets speed &amp; acceleration to factory defaults.\n"
  "          </div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-danger\" onclick=\"putNoBody('/setup/restoreRotationMotorSettings')\">RESTORE DEFAULTS</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "    </div>\n"
  "  </div>\n"
  "\n"
  "  <!-- ===== SHUTTER TAB ===== -->\n"
  "  <div class=\"tab-pane\" id=\"tab-shutter\">\n"
  "    <div class=\"section-label\">Shutter Controller</div>\n"
  "    <div class=\"grid\">\n"
  "\n"
  "      <!-- Shutter present -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Shutter Present</span>\n"
  "          <span class=\"method-badge badge-get\">GET</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-shutpres\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/shutterPresentState','val-shutpres',v=>v.value?'YES':'NO')\">GET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Shutter open order -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Shutter Open Order</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-shutorder\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/shutterOpenOrder','val-shutorder',v=>v)\">GET</button>\n"
  "            <select id=\"in-shutorder\">\n"
  "              <option value=\"BOTTOM_FIRST\">BOTTOM_FIRST</option>\n"
  "              <option value=\"TOP_FIRST\">TOP_FIRST</option>\n"
  "            </select>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/shutterOpenOrder','in-shutorder','val-shutorder',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Shutter WiFi SSID -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Shutter WiFi SSID</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-ssid\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/wifiSSID','val-ssid',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"text\" id=\"in-ssid\" placeholder=\"SSID\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/wifiSSID','in-ssid','val-ssid',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Shutter speed -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Shutter Speed (steps/s)</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-sspeed\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/shutterSpeed','val-sspeed',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"number\" id=\"in-sspeed\" placeholder=\"steps/s\" min=\"1\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/shutterSpeed','in-sspeed','val-sspeed',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Shutter acceleration -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Shutter Acceleration (steps/s²)</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-sacc\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/shutterAcceleration','val-sacc',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"number\" id=\"in-sacc\" placeholder=\"steps/s²\" min=\"1\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/shutterAcceleration','in-sacc','val-sacc',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Shutter voltage -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Shutter Voltage</span>\n"
  "          <span class=\"method-badge badge-get\">GET</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-svolt\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/shutterVoltage','val-svolt',v=>JSON.stringify(v)+'V')\">GET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Shutter voltage cutoff -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Voltage Cutoff</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-vcutoff\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/shutterVoltageCutoff','val-vcutoff',v=>JSON.stringify(v)+'V')\">GET</button>\n"
  "            <input type=\"number\" id=\"in-vcutoff\" placeholder=\"volts\" min=\"0\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/shutterVoltageCutoff','in-vcutoff','val-vcutoff',v=>JSON.stringify(v)+'V')\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Restore shutter defaults -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Restore Shutter Motor Defaults</span>\n"
  "          <span class=\"method-badge badge-put\">PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div style=\"font-size:.8rem;color:var(--muted);margin-bottom:12px;\">\n"
  "            Resets shutter speed &amp; acceleration to factory defaults.\n"
  "          </div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-danger\" onclick=\"putNoBody('/setup/restoreShutterMotorSettings')\">RESTORE DEFAULTS</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "    </div>\n"
  "  </div>\n"
  "\n"
  "  <!-- ===== NETWORK TAB ===== -->\n"
  "  <div class=\"tab-pane\" id=\"tab-network\">\n"
  "    <div class=\"section-label\">Network Settings</div>\n"
  "    <div class=\"grid\">\n"
  "\n"
  "      <!-- DHCP -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">DHCP</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-dhcp\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/useDHCP','val-dhcp',v=>JSON.stringify(v))\">GET</button>\n"
  "            <select id=\"in-dhcp\">\n"
  "              <option value=\"true\">Enabled</option>\n"
  "              <option value=\"false\">Disabled</option>\n"
  "            </select>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/useDHCP','in-dhcp','val-dhcp',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- MAC Address (GET only) -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">MAC Address</span>\n"
  "          <span class=\"method-badge badge-get\">GET</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-mac\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/macAddress','val-mac',v=>JSON.stringify(v))\">GET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- IP Address -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">IP Address</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-ip\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/ipAddress','val-ip',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"text\" id=\"in-ip\" placeholder=\"x.x.x.x\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/ipAddress','in-ip','val-ip',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Subnet mask -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Subnet Mask</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-mask\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/subnetMask','val-mask',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"text\" id=\"in-mask\" placeholder=\"255.255.255.0\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/subnetMask','in-mask','val-mask',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Gateway -->\n"
  "      <div class=\"card\">\n"
  "        <div class=\"card-head\">\n"
  "          <span class=\"card-title\">Gateway IP</span>\n"
  "          <span class=\"method-badge badge-both\">GET / PUT</span>\n"
  "        </div>\n"
  "        <div class=\"card-body\">\n"
  "          <div class=\"val-display unknown\" id=\"val-gw\">—</div>\n"
  "          <div class=\"card-actions\">\n"
  "            <button class=\"btn btn-get\" onclick=\"getVal('/setup/ipGateway','val-gw',v=>JSON.stringify(v))\">GET</button>\n"
  "            <input type=\"text\" id=\"in-gw\" placeholder=\"x.x.x.x\"/>\n"
  "            <button class=\"btn btn-put\" onclick=\"putVal('/setup/ipGateway','in-gw','val-gw',v=>JSON.stringify(v))\">SET</button>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "    </div>\n"
  "  </div>\n"
  "\n"
  "  <!-- LOG -->\n"
  "  <div class=\"log-panel\">\n"
  "    <div class=\"log-head\">\n"
  "      <span class=\"log-head-title\">▸ ACTIVITY LOG</span>\n"
  "      <button class=\"btn btn-get\" style=\"font-size:.65rem;padding:3px 10px;\" onclick=\"clearLog()\">CLEAR</button>\n"
  "    </div>\n"
  "    <div id=\"log\"></div>\n"
  "  </div>\n"
  "\n"
  "</div><!-- /shell -->\n"
  "\n"
  "<script>\n"
  "// ─── Helpers ──────────────────────────────────────────────────────────────────\n"
  "function baseURL() { return ''; }\n"
  "\n"
  "function ts() {\n"
  "  return new Date().toLocaleTimeString('en-GB',{hour12:false});\n"
  "}\n"
  "\n"
  "function log(msg, cls='log-info') {\n"
  "  const div = document.getElementById('log');\n"
  "  const entry = document.createElement('div');\n"
  "  entry.className = 'log-entry';\n"
  "  entry.innerHTML = `<span class=\"log-ts\">${ts()}</span><span class=\"${cls}\">${msg}</span>`;\n"
  "  div.prepend(entry);\n"
  "}\n"
  "\n"
  "function clearLog() { document.getElementById('log').innerHTML = ''; }\n"
  "\n"
  "function setConnStatus(state) {\n"
  "  const el = document.getElementById('conn-status');\n"
  "  el.className = state === 'ok' ? 'ok' : state === 'err' ? 'err' : '';\n"
  "}\n"
  "\n"
  "function setDisplay(id, text) {\n"
  "  const el = document.getElementById(id);\n"
  "  el.textContent = text;\n"
  "  el.classList.remove('unknown');\n"
  "}\n"
  "\n"
  "// ─── Core API call ─────────────────────────────────────────────────────────────\n"
  "async function apiCall(method, path, params={}) {\n"
  "  let url = baseURL() + path;\n"
  "  if (method === 'GET' && Object.keys(params).length) {\n"
  "    url += '?' + new URLSearchParams(params);\n"
  "  }\n"
  "  let opts = { method };\n"
  "  if (method === 'PUT' && Object.keys(params).length) {\n"
  "    url += '?' + new URLSearchParams(params);\n"
  "  }\n"
  "\n"
  "  log(`${method} ${path}${Object.keys(params).length?' ('+JSON.stringify(params)+')':''}`, 'log-info');\n"
  "\n"
  "  const resp = await fetch(url, { ...opts, signal: AbortSignal.timeout(5000) });\n"
  "  setConnStatus('ok');\n"
  "  let data;\n"
  "  try { data = await resp.json(); } catch { data = null; }\n"
  "  if (!resp.ok) {\n"
  "    const msg = data ? `Error ${data.ErrorNumber}: ${data.ErrorMessage}` : `HTTP ${resp.status}`;\n"
  "    log(`✗ ${msg}`, 'log-err');\n"
  "    throw new Error(msg);\n"
  "  }\n"
  "  log(`✓ ${resp.status} ${JSON.stringify(data)}`, 'log-ok');\n"
  "  return data;\n"
  "}\n"
  "\n"
  "// ─── GET helper ───────────────────────────────────────────────────────────────\n"
  "async function getVal(path, displayId, formatter) {\n"
  "  const el = document.getElementById(displayId);\n"
  "  el.innerHTML = '<span class=\"spinner\"></span>';\n"
  "  try {\n"
  "    const data = await apiCall('GET', path);\n"
  "    setDisplay(displayId, formatter(data));\n"
  "  } catch(e) {\n"
  "    el.textContent = 'ERR';\n"
  "    el.classList.add('unknown');\n"
  "    setConnStatus('err');\n"
  "  }\n"
  "}\n"
  "\n"
  "// ─── PUT helper ───────────────────────────────────────────────────────────────\n"
  "async function putVal(path, inputId, displayId, formatter) {\n"
  "  const inp = document.getElementById(inputId);\n"
  "  const val = inp.value;\n"
  "  if (val === '') { log('✗ No value provided', 'log-err'); return; }\n"
  "  const el = document.getElementById(displayId);\n"
  "  el.innerHTML = '<span class=\"spinner\"></span>';\n"
  "  try {\n"
  "    const data = await apiCall('PUT', path, { value: val });\n"
  "    // after PUT, refresh with GET\n"
  "    await getVal(path, displayId, formatter);\n"
  "  } catch(e) {\n"
  "    el.textContent = 'ERR';\n"
  "    el.classList.add('unknown');\n"
  "    setConnStatus('err');\n"
  "  }\n"
  "}\n"
  "\n"
  "// ─── PUT no body ──────────────────────────────────────────────────────────────\n"
  "async function putNoBody(path) {\n"
  "  try {\n"
  "    await apiCall('PUT', path);\n"
  "  } catch(e) { setConnStatus('err'); }\n"
  "}\n"
  "\n"
  "// ─── Overview refresh ─────────────────────────────────────────────────────────\n"
  "async function refreshOverview() {\n"
  "  // Home position → azimuth display\n"
  "  try {\n"
  "    const h = await apiCall('GET', '/setup/homePosition');\n"
  "    const az = parseFloat(h?.value ?? 0);\n"
  "    document.getElementById('az-label').innerHTML = `${az.toFixed(1)}°<small>HOME AZ</small>`;\n"
  "    document.getElementById('az-pointer').style.transform = `rotate(${az}deg)`;\n"
  "  } catch {}\n"
  "\n"
  "  // Calibration chip\n"
  "  try {\n"
  "    const c = await apiCall('GET', '/setup/domeCalibrate');\n"
  "    const dot = document.getElementById('chip-calib');\n"
  "    const state = c?.value ?? '';\n"
  "    dot.className = 'chip-dot ' + (state === 'NOT_CALIBRATING' ? 'on' : state ? 'warn' : '');\n"
  "  } catch {}\n"
  "\n"
  "  // Shutter present chip\n"
  "  try {\n"
  "    const s = await apiCall('GET', '/setup/shutterPresentState');\n"
  "    const dot = document.getElementById('chip-shutter');\n"
  "    dot.className = 'chip-dot ' + (s?.value ? 'on' : 'off');\n"
  "  } catch {}\n"
  "\n"
  "  // Env condition chip\n"
  "  try {\n"
  "    const e = await apiCall('GET', '/setup/envCondition');\n"
  "    const dot = document.getElementById('chip-env');\n"
  "    dot.className = 'chip-dot on';\n"
  "  } catch {}\n"
  "\n"
  "  // DHCP chip\n"
  "  try {\n"
  "    const d = await apiCall('GET', '/setup/useDHCP');\n"
  "    const dot = document.getElementById('chip-dhcp');\n"
  "    dot.className = 'chip-dot ' + (d === true || d?.value === true ? 'on' : 'warn');\n"
  "  } catch {}\n"
  "}\n"
  "\n"
  "// ─── Tabs ─────────────────────────────────────────────────────────────────────\n"
  "document.querySelectorAll('.tab-btn').forEach(btn => {\n"
  "  btn.addEventListener('click', () => {\n"
  "    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));\n"
  "    document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));\n"
  "    btn.classList.add('active');\n"
  "    document.getElementById('tab-' + btn.dataset.tab).classList.add('active');\n"
  "  });\n"
  "});\n"
  "\n"
  "// ─── Startup ──────────────────────────────────────────────────────────────────\n"
  "log('Dome Controller UI ready. Configure host and click GET to communicate.', 'log-info');\n"
  "</script>\n"
  "</body>\n"
  "</html>\n";

#endif /* DOME_CONTROLLER_HTML_H */