openapi: 3.0.3

info:
  title: RTI-Zone Dome API
  version: 1.0.0
  description: This API describes communications with the RTI-Zone dome server.
  contact:
    name: RTI-Zone
    url: https://rti-zone.org/

externalDocs:
  description: Find out more about the RTI-Zone dome controller
  url: https://rti-zone.org/astro_dome_control.php

servers:
- url: http://{host}/
  description: hostname or ip address of dome controller
  variables:
    host:
      default: 192.168.0.99
      description: The hostname or ip address.

paths:
  /setup/homePosition:
    get:
      summary: Get the controller home position
      description: |
        Retrieve the controller home position.
      operationId: getHomePosition
      responses:
        '200':
          description: Position successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Position'
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Positions
    put:
      summary: Set the controller home position
      description: |
        Set the controller home position which is then used to properly calculate
        azimuth to motor step position.
      operationId: setHomePosition
      parameters:
      - name: value
        in: query
        description: New home position azimuth in degrees
        required: true
        schema:
          type: number
          format: float
      responses:
        '200':
          description: Position successfully set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Position'
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Positions

  /setup/parkPosition:
    get:
      summary: Get the controller park position
      description: |
        Retrieve the controller park position.
      operationId: getParkPosition
      responses:
        '200':
          description: Position successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Position'
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Positions
    put:
      summary: Set the controller park position
      description: |
        Set the controller park position.
      operationId: setParkPosition
      parameters:
      - name: value
        in: query
        description: New park position azimuth in degrees
        required: true
        schema:
          type: number
          format: float
      responses:
        '200':
          description: Position successfully set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Position'
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Positions

  /setup/reverseDirection:
    get:
      summary: Get the controller default rotation direction
      description: |
        Retrieve the controller rotation direction.
      operationId: getReverseDirection
      responses:
        '200':
          description: Direction successfully retrieved
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Positions
    put:
      summary: Set the controller direction, normal or reversed
      description: |
        Set the controller direction, normal or reversed.
      operationId: setReverseDirection
      parameters:
      - name: value
        in: query
        description: reversed true or false
        required: true
        schema:
          type: boolean
      responses:
        '200':
          description: Direction successfully set
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Positions

  /setup/useDHCP:
    get:
      summary: Get the controller DHCP setting
      description: |
        Retrieve the controller DHCP setting.
      operationId: getDHCPEnabled
      responses:
        '200':
          description: DHCP value successfully retrieved
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking
    put:
      summary: Set the controller DHCP setting
      description: |
        Set the controller DHCP setting.
      operationId: setDHCPEnabled
      parameters:
      - name: value
        in: query
        description: DHCP enabled is true or false
        required: true
        schema:
          type: boolean
      responses:
        '200':
          description: DHCP successfully set
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking

  /setup/macAddress:
    get:
      summary: Get the controller MAC Address
      description: |
        Retrieve the controller MAC Address.
      operationId: getMACAddress
      responses:
        '200':
          description: MAC Address value successfully retrieved
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking

  /setup/ipAddress:
    get:
      summary: Get the controller IP Address
      description: |
        Retrieve the controller IP Address.
      operationId: getIpAddress
      responses:
        '200':
          description: IP Address value successfully retrieved
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking
    put:
      summary: Set the controller IP Address
      description: |
        Set the controller IP Address.
      operationId: setIpAddress
      parameters:
      - name: value
        in: query
        description: IP Address 
        required: true
        schema:
          type: string
      responses:
        '200':
          description: IP Address successfully set
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking

  /setup/subnetMask:
    get:
      summary: Get the controller subnet mask
      description: |
        Retrieve the controller subnet mask.
      operationId: getSubnetMask
      responses:
        '200':
          description: Subnet mask value successfully retrieved
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking
    put:
      summary: Set the controller subnet mask
      description: |
        Set the controller subnet mask.
      operationId: setSubnetMask
      parameters:
      - name: value
        in: query
        description: Subnet mask 
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Subnet mask successfully set
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking

  /setup/ipGateway:
    get:
      summary: Get the controller gateway IP
      description: |
        Retrieve the controller gateway IP.
      operationId: getGatewayIP
      responses:
        '200':
          description: Gateway IP value successfully retrieved
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking
    put:
      summary: Set the controller gateway IP
      description: |
        Set the controller gateway IP.
      operationId: setGatewayIP
      parameters:
      - name: value
        in: query
        description: Gateway IP 
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Gateway IP successfully set
        '400':
          $ref: '#/components/responses/Response400'
      tags:
      - Networking

components:
  schemas:
    Position:
      type: object
      properties:
        value:
          type: number
          format: float
          description: position in degrees
      required:
      - value
    Direction:
      type: object
      properties:
        value:
          type: number
          format: float
          description: position in degrees
      required:
      - value

    ErrorCode:
      type: integer
      description: Error codes. Same as Alpaca
      enum:
      - 0
      - 1024
      - 1025
      - 1026
      - 1031
      - 1032
      - 1033
      - 1035
      - 1036

    Response400ErrorInfo:
      type: object
      properties:
        ErrorNumber:
          $ref: '#/components/schemas/ErrorCode'
        ErrorMessage:
          type: string
      required:
      - ErrorNumber
      - ErrorMessage

  examples:
    ERROR_BUSY_SLEWING:
      value: { ErrorNumber: 1035, ErrorMessage: "Controller is busy slewing to a new position." }
      description: No Error
    ERROR_BUSY_CALIBRATING:
      value: { ErrorNumber: 1035, ErrorMessage: "Controller is busy calibrating." }
      description: Controller is busy

  responses:
    Response400:
      description: Dome controller error. Additional information encoded in the response content.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response400ErrorInfo'
          examples:
            ERROR_BUSY_SLEWING:
              $ref: '#/components/examples/ERROR_BUSY_SLEWING'
            ERROR_BUSY_CALIBRATING:
              $ref: '#/components/examples/ERROR_BUSY_CALIBRATING'
